'use strict';

const { getSharedHeadAssets, getSharedStyles, getSharedNav } = require('./ui_shared');

function getKnowledgeHTML(user) { return `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>ATERUM — Decision Knowledge</title>
${getSharedHeadAssets()}
<script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script>
<script src="https://unpkg.com/cytoscape@3.30.3/dist/cytoscape.min.js"></script>
<style>
${getSharedStyles()}
:root{--k-bg:#070b11;--k-panel:#0e151f;--k-panel2:#121c28;--k-line:#243142;--k-text:#edf5ff;--k-muted:#8fa1b5;--k-blue:#52a8ff;--k-green:#35d6a0;--k-red:#ff667d;--k-amber:#f0bd65;--k-violet:#a18aff}
*{box-sizing:border-box}body{margin:0;background:var(--k-bg);color:var(--k-text);font-family:Inter,sans-serif;min-height:100vh;letter-spacing:0}.knowledge-shell{max-width:1680px;margin:0 auto;padding:24px 24px 72px}.knowledge-head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:20px}.knowledge-head h1{font:800 28px/1.1 'Inter Tight',sans-serif;margin:0;letter-spacing:0}.knowledge-head p{margin:6px 0 0;color:var(--k-muted);font-size:12px}.status-row{display:flex;gap:8px;flex-wrap:wrap}.status-chip{border:1px solid var(--k-line);background:var(--k-panel);padding:7px 10px;border-radius:6px;font:600 10px/1 JetBrains Mono;color:var(--k-muted)}.status-chip.live{color:var(--k-green);border-color:rgba(53,214,160,.35)}
.view-tabs{display:flex;gap:6px;overflow:auto;border-bottom:1px solid var(--k-line);margin-bottom:18px;padding-bottom:8px}.view-tab{border:1px solid transparent;background:none;color:var(--k-muted);height:34px;padding:0 12px;border-radius:6px;display:inline-flex;align-items:center;gap:7px;font:700 10px/1 Inter;text-transform:uppercase;cursor:pointer;white-space:nowrap}.view-tab svg{width:15px}.view-tab.active{background:var(--k-panel2);border-color:var(--k-line);color:var(--k-blue)}.view{display:none}.view.active{display:block}
.explorer-grid{display:grid;grid-template-columns:330px minmax(0,1fr);gap:16px}.decision-sidebar{border-right:1px solid var(--k-line);padding-right:16px;min-width:0}.toolbar{display:flex;gap:8px;margin-bottom:12px}.input,.select{width:100%;height:36px;border:1px solid var(--k-line);background:var(--k-panel);color:var(--k-text);border-radius:6px;padding:0 10px;font:500 11px Inter;outline:none}.input:focus,.select:focus{border-color:var(--k-blue)}.decision-list{display:flex;flex-direction:column;gap:7px;max-height:calc(100vh - 220px);overflow:auto;padding-right:3px}.decision-item{width:100%;text-align:left;border:1px solid var(--k-line);background:var(--k-panel);color:var(--k-text);border-radius:6px;padding:11px;cursor:pointer;display:grid;grid-template-columns:1fr auto;gap:5px 10px}.decision-item:hover,.decision-item.active{border-color:var(--k-blue);background:var(--k-panel2)}.decision-symbol{font:800 13px 'Inter Tight'}.decision-meta{font:500 9px JetBrains Mono;color:var(--k-muted)}.decision-score{font:700 12px JetBrains Mono;color:var(--k-blue)}.tag{display:inline-flex;align-items:center;border:1px solid var(--k-line);border-radius:4px;padding:3px 6px;font:700 8px Inter;text-transform:uppercase}.tag.accept{color:var(--k-green);border-color:rgba(53,214,160,.3)}.tag.reject{color:var(--k-red);border-color:rgba(255,102,125,.3)}
.decision-main{min-width:0}.empty{border:1px dashed var(--k-line);min-height:280px;display:grid;place-items:center;color:var(--k-muted);font-size:12px}.summary-band{border-bottom:1px solid var(--k-line);padding:4px 0 18px;margin-bottom:18px;display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.summary-band h2{margin:0;font:800 24px 'Inter Tight'}.summary-band .reason{color:var(--k-muted);font-size:12px;line-height:1.55;max-width:820px;margin-top:7px}.metric-strip{display:grid;grid-template-columns:repeat(6,minmax(100px,1fr));border:1px solid var(--k-line);border-radius:6px;overflow:hidden;margin-bottom:18px}.metric{padding:13px;border-right:1px solid var(--k-line);background:var(--k-panel)}.metric:last-child{border-right:0}.metric label{display:block;color:var(--k-muted);font:700 8px Inter;text-transform:uppercase;margin-bottom:6px}.metric strong{font:700 15px JetBrains Mono;overflow-wrap:anywhere}.section{padding:18px 0;border-bottom:1px solid var(--k-line)}.section:last-child{border-bottom:0}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.section-title{display:flex;align-items:center;gap:8px;font:800 11px Inter;text-transform:uppercase}.section-title svg{width:16px;color:var(--k-blue)}.context-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.datum{background:var(--k-panel);border:1px solid var(--k-line);border-radius:6px;padding:11px;min-height:66px}.datum span{display:block;color:var(--k-muted);font:700 8px Inter;text-transform:uppercase;margin-bottom:6px}.datum strong{font:600 11px/1.35 JetBrains Mono;overflow-wrap:anywhere}.timeline{position:relative;padding-left:20px}.timeline:before{content:'';position:absolute;left:5px;top:4px;bottom:4px;width:1px;background:var(--k-line)}.timeline-event{position:relative;padding:0 0 14px 14px}.timeline-event:before{content:'';position:absolute;left:-19px;top:4px;width:7px;height:7px;border-radius:50%;background:var(--k-blue);border:2px solid var(--k-bg)}.timeline-time{font:600 9px JetBrains Mono;color:var(--k-muted)}.timeline-title{font:700 11px Inter;margin:3px 0}.timeline-detail{font:500 10px/1.45 Inter;color:var(--k-muted)}
.evidence-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.evidence-group{border:1px solid var(--k-line);background:var(--k-panel);padding:11px;border-radius:6px}.evidence-group h4{margin:0 0 8px;font:800 9px Inter;text-transform:uppercase;color:var(--k-blue)}.evidence-row{font:500 10px/1.5 JetBrains Mono;color:var(--k-muted);overflow-wrap:anywhere}.missing{color:var(--k-amber);font-size:10px;line-height:1.5;margin-top:8px}
.graph-layout{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:16px}.graph-canvas{height:650px;border:1px solid var(--k-line);background:var(--k-panel);border-radius:6px}.graph-inspector{border-left:1px solid var(--k-line);padding-left:16px}.graph-inspector pre{font:500 10px/1.5 JetBrains Mono;white-space:pre-wrap;overflow-wrap:anywhere;color:var(--k-muted)}
.diff-controls{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;margin-bottom:18px}.btn{height:36px;border:1px solid var(--k-blue);background:rgba(82,168,255,.12);color:var(--k-blue);border-radius:6px;padding:0 14px;font:800 10px Inter;text-transform:uppercase;cursor:pointer}.diff-table,.rules-table{width:100%;border-collapse:collapse}.diff-table th,.diff-table td,.rules-table th,.rules-table td{padding:10px;border-bottom:1px solid var(--k-line);text-align:left;font-size:10px;vertical-align:top}.diff-table th,.rules-table th{color:var(--k-muted);font:700 8px Inter;text-transform:uppercase;position:sticky;top:56px;background:var(--k-bg);z-index:1}.mono{font-family:JetBrains Mono}.positive{color:var(--k-green)}.negative{color:var(--k-red)}.muted{color:var(--k-muted)}.rules-wrap{overflow:auto;max-height:680px}.rule-name{font-weight:700;min-width:190px}.loading-line{height:2px;background:var(--k-blue);animation:load 1.2s infinite;transform-origin:left}@keyframes load{0%{transform:scaleX(.05)}50%{transform:scaleX(1)}100%{transform:scaleX(.05);transform-origin:right}}
@media(max-width:1100px){.explorer-grid{grid-template-columns:1fr}.decision-sidebar{border-right:0;border-bottom:1px solid var(--k-line);padding:0 0 14px}.decision-list{max-height:280px}.metric-strip{grid-template-columns:repeat(3,1fr)}.context-grid{grid-template-columns:repeat(2,1fr)}.graph-layout{grid-template-columns:1fr}.graph-inspector{border-left:0;padding-left:0}.evidence-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:680px){.knowledge-shell{padding:16px 12px 60px}.knowledge-head{align-items:flex-start;flex-direction:column}.metric-strip{grid-template-columns:repeat(2,1fr)}.metric:nth-child(2n){border-right:0}.context-grid,.evidence-grid{grid-template-columns:1fr}.diff-controls{grid-template-columns:1fr}.graph-canvas{height:480px}}
</style>
</head>
<body>
${getSharedNav('knowledge', user, 'blue')}
<main class="knowledge-shell">
  <header class="knowledge-head"><div><h1>Decision Knowledge</h1><p id="headSub">Trazabilidad determinista de decisiones persistidas</p></div><div class="status-row"><span class="status-chip live">● DATA ONLY</span><span class="status-chip" id="decisionCount">— decisiones</span><span class="status-chip" id="loadTime">— ms</span></div></header>
  <nav class="view-tabs" aria-label="Vistas de conocimiento">
    <button class="view-tab active" data-view="explorer"><i data-lucide="list-tree"></i>Decision Explorer</button>
    <button class="view-tab" data-view="graph"><i data-lucide="waypoints"></i>Knowledge Graph</button>
    <button class="view-tab" data-view="diff"><i data-lucide="git-compare-arrows"></i>Decision Diff</button>
    <button class="view-tab" data-view="rules"><i data-lucide="shield-check"></i>Rule Impact</button>
    <button class="view-tab" data-view="changes"><i data-lucide="history"></i>Change History</button>
  </nav>
  <section class="view active" id="view-explorer"><div class="explorer-grid"><aside class="decision-sidebar"><div class="toolbar"><input class="input" id="decisionSearch" placeholder="Símbolo o ID"><select class="select" id="decisionKind"><option value="">Todas</option><option value="trade">Trades</option><option value="rejection">Rechazos</option></select></div><div class="decision-list" id="decisionList"><div class="loading-line"></div></div></aside><div class="decision-main" id="decisionDetail"><div class="empty">Selecciona una decisión</div></div></div></section>
  <section class="view" id="view-graph"><div class="graph-layout"><div id="knowledgeGraph" class="graph-canvas"></div><aside class="graph-inspector"><div class="section-title"><i data-lucide="scan-search"></i>Inspector</div><pre id="graphInspector">Selecciona un nodo</pre></aside></div></section>
  <section class="view" id="view-diff"><div class="diff-controls"><select class="select" id="diffLeft"></select><select class="select" id="diffRight"></select><button class="btn" id="compareBtn">Comparar</button></div><div id="diffResult" class="empty">Selecciona dos decisiones</div></section>
  <section class="view" id="view-rules"><div class="rules-wrap"><table class="rules-table"><thead><tr><th>Regla</th><th>Origen</th><th>Estado</th><th>Trades</th><th>PnL</th><th>Drawdown</th><th>Impacto</th><th>Evidencia</th></tr></thead><tbody id="rulesBody"></tbody></table></div></section>
  <section class="view" id="view-changes"><div class="timeline" id="changesTimeline"></div></section>
</main>
<script>
const state={decisions:[],selected:null,detail:null,timeline:null,evidence:null,graph:null,rules:[],cy:null};
const esc=value=>String(value??'N/D').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fmtDate=value=>value?new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'medium',timeZone:'UTC'}).format(new Date(value))+' UTC':'N/D';
const fmtNum=(value,d=2)=>value==null?'N/D':Number(value).toLocaleString('en-US',{maximumFractionDigits:d});
const money=value=>value==null?'N/D':(Number(value)>=0?'+':'-')+'$'+Math.abs(Number(value)).toFixed(2);
const valueClass=value=>Number(value)>0?'positive':Number(value)<0?'negative':'';
async function api(path){const started=performance.now(),response=await fetch(path);const body=await response.json();if(!response.ok)throw new Error(body.error||'Error API');document.getElementById('loadTime').textContent=Math.round(performance.now()-started)+' ms';return body}
function icon(){if(window.lucide)lucide.createIcons()}
function setView(name){document.querySelectorAll('.view-tab').forEach(el=>el.classList.toggle('active',el.dataset.view===name));document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id==='view-'+name));if(name==='graph'&&state.graph)renderGraph();}
document.querySelectorAll('.view-tab').forEach(el=>el.onclick=()=>setView(el.dataset.view));
function decisionLabel(row){return row.ref+' · '+row.symbol+' · '+fmtDate(row.event_at)}
function renderList(){const q=document.getElementById('decisionSearch').value.trim().toUpperCase(),kind=document.getElementById('decisionKind').value;const rows=state.decisions.filter(row=>(!kind||row.kind===kind)&&(!q||row.symbol.includes(q)||row.ref.toUpperCase().includes(q)));document.getElementById('decisionList').innerHTML=rows.map(row=>\`<button class="decision-item \${state.selected===row.ref?'active':''}" data-ref="\${esc(row.ref)}"><div><div class="decision-symbol">\${esc(row.symbol)} <span class="tag \${row.kind==='trade'?'accept':'reject'}">\${row.kind==='trade'?'Trade':'Reject'}</span></div><div class="decision-meta">\${esc(row.direction)} · \${fmtDate(row.event_at)}</div></div><div class="decision-score">\${fmtNum(row.score,1)}</div><div class="decision-meta">\${esc(row.ref)}</div><div class="\${valueClass(row.pnl_usdt)} mono">\${row.pnl_usdt==null?'':money(row.pnl_usdt)}</div></button>\`).join('')||'<div class="empty">Sin resultados</div>';document.querySelectorAll('.decision-item').forEach(el=>el.onclick=()=>selectDecision(el.dataset.ref));}
function metric(label,value,cls=''){return \`<div class="metric"><label>\${esc(label)}</label><strong class="\${cls}">\${esc(value)}</strong></div>\`}
function datum(label,value){return \`<div class="datum"><span>\${esc(label)}</span><strong>\${esc(value)}</strong></div>\`}
function renderDetail(){const d=state.detail,t=state.timeline,e=state.evidence;if(!d)return;const trade=d.trade||{},m=d.marketContext||{},fd=d.finalDecision||{};const sourceGroups=Object.entries(e.sources||{}).filter(([,rows])=>rows.length);document.getElementById('decisionDetail').innerHTML=\`
<div class="summary-band"><div><h2>\${esc(d.symbol)} · \${esc(fd.action)}</h2><div class="reason">\${esc(fd.reason)}</div></div><span class="tag \${fd.accepted?'accept':'reject'}">\${fd.accepted?'Aceptada':'Rechazada'}</span></div>
<div class="metric-strip">\${metric('Score base',fmtNum(fd.baseScore,1))}\${metric('Score final',fmtNum(fd.finalScore,1))}\${metric('Threshold',fmtNum(fd.threshold,1))}\${metric('Learning',fmtNum(fd.learningFactor,3))}\${metric('PnL',money(trade.pnlUsdt),valueClass(trade.pnlUsdt))}\${metric('R final',trade.rFinal==null?'N/D':fmtNum(trade.rFinal,2)+'R',valueClass(trade.rFinal))}</div>
<section class="section"><div class="section-head"><div class="section-title"><i data-lucide="radar"></i>Contexto persistido</div></div><div class="context-grid">\${datum('Research',d.research?'#'+d.research.id+' · '+d.research.report_type:'Sin evidencia')}\${datum('Learning',d.learning?'#'+d.learning.id+' · '+d.learning.action:'Sin evidencia')}\${datum('Regimen',m.regime)}\${datum('Macro',m.macroBias)}\${datum('Fear & Greed',m.fearGreed)}\${datum('4H',m.tf4hStatus)}\${datum('Imagen',d.imageAnalysis.available?(d.imageAnalysis.approved?'Aprobada':'No aprobada'):'Sin evidencia')}\${datum('Capital Guard',d.capitalGuard?(d.capitalGuard.halted?'Halted':'Permitido'):'Sin evidencia')}\${datum('ATR',m.atrPct==null?'N/D':m.atrPct+'%')}\${datum('RSI',m.rsi14)}\${datum('Volumen',m.volumeRatio==null?'N/D':m.volumeRatio+'x')}\${datum('Simulator',d.simulator.available?'Threshold '+d.simulator.threshold:'Sin snapshot')}\${datum('SL / TP',trade.sl==null?'N/D':trade.sl+' / '+trade.tp)}\${datum('Stage final',trade.trailingStage)}\${datum('Noticias','Sin evidencia histórica')}\${datum('n8n',d.n8nExecution?.id?'Execution #'+d.n8nExecution.id:'Sin evidencia')}</div></section>
<section class="section"><div class="section-head"><div class="section-title"><i data-lucide="clock-3"></i>Timeline</div><span class="status-chip">\${t.events.length} eventos</span></div><div class="timeline">\${t.events.map(row=>\`<div class="timeline-event"><div class="timeline-time">\${fmtDate(row.at)}</div><div class="timeline-title">\${esc(row.title)}</div><div class="timeline-detail">\${esc(row.detail)} · \${esc(row.evidence)}</div></div>\`).join('')}</div></section>
<section class="section"><div class="section-head"><div class="section-title"><i data-lucide="file-check-2"></i>Evidence</div></div><div class="evidence-grid">\${sourceGroups.map(([name,rows])=>\`<div class="evidence-group"><h4>\${esc(name)} · \${rows.length}</h4>\${rows.map(row=>\`<div class="evidence-row">\${esc(row.table)}#\${esc(row.id??'snapshot')} \${row.status?'· '+esc(row.status):''}</div>\`).join('')}</div>\`).join('')}</div>\${(e.missing||[]).map(row=>\`<div class="missing">△ \${esc(row)}</div>\`).join('')}</section>\`;icon();}
async function selectDecision(ref){state.selected=ref;renderList();document.getElementById('decisionDetail').innerHTML='<div class="loading-line"></div>';const encoded=encodeURIComponent(ref);try{const [detail,timeline,evidence,graph]=await Promise.all([api('/api/knowledge/trade/'+encoded),api('/api/knowledge/timeline/'+encoded),api('/api/knowledge/evidence/'+encoded),api('/api/knowledge/graph/'+encoded)]);Object.assign(state,{detail,timeline,evidence,graph});renderDetail();if(document.getElementById('view-graph').classList.contains('active'))renderGraph();}catch(error){document.getElementById('decisionDetail').innerHTML='<div class="empty">'+esc(error.message)+'</div>'}}
function renderGraph(){if(!state.graph||!window.cytoscape)return;const colors={trade:'#35d6a0',rejection:'#ff667d',scan:'#52a8ff',research:'#a18aff',learning:'#f0bd65',rule:'#f0bd65',recommendation:'#a18aff',review:'#8fa1b5',change:'#52a8ff',post_trade:'#35d6a0',outcome:'#35d6a0'};const elements=[...state.graph.nodes.map(n=>({data:{id:n.id,label:n.label,type:n.type,raw:n.data,color:colors[n.type]||'#8fa1b5'}})),...state.graph.edges.map((e,i)=>({data:{id:'e'+i,source:e.from,target:e.to,label:e.relation}}))];if(state.cy)state.cy.destroy();state.cy=cytoscape({container:document.getElementById('knowledgeGraph'),elements,layout:{name:'breadthfirst',directed:true,padding:28,spacingFactor:1.25},style:[{selector:'node',style:{'background-color':'data(color)','label':'data(label)','color':'#edf5ff','font-size':10,'font-family':'Inter','text-wrap':'wrap','text-max-width':110,'text-valign':'bottom','text-margin-y':8,'width':30,'height':30,'border-width':2,'border-color':'#243142'}},{selector:'edge',style:{'width':1.2,'line-color':'#34465d','target-arrow-color':'#34465d','target-arrow-shape':'triangle','curve-style':'bezier','label':'data(label)','font-size':7,'color':'#8fa1b5','text-background-color':'#0e151f','text-background-opacity':1,'text-background-padding':2}}]});state.cy.on('tap','node',event=>{const raw=event.target.data('raw');document.getElementById('graphInspector').textContent=JSON.stringify(raw,null,2)});}
async function compare(){const id1=document.getElementById('diffLeft').value,id2=document.getElementById('diffRight').value;if(!id1||!id2)return;const root=document.getElementById('diffResult');root.className='';root.innerHTML='<div class="loading-line"></div>';try{const d=await api('/api/knowledge/diff?id1='+encodeURIComponent(id1)+'&id2='+encodeURIComponent(id2));root.innerHTML=\`<table class="diff-table"><thead><tr><th>Campo</th><th>\${esc(d.left.ref)}</th><th>\${esc(d.right.ref)}</th></tr></thead><tbody>\${d.differences.map(row=>\`<tr><td>\${esc(row.label)}</td><td class="mono">\${esc(row.left)}</td><td class="mono">\${esc(row.right)}</td></tr>\`).join('')}</tbody></table>\`}catch(error){root.className='empty';root.textContent=error.message}}
function renderRules(){document.getElementById('rulesBody').innerHTML=state.rules.map(rule=>\`<tr><td class="rule-name">\${esc(rule.name)}<div class="muted">\${fmtDate(rule.date)}</div></td><td>\${esc(rule.actor)}<div class="muted">\${rule.recommendations.map(r=>'#'+r.id).join(', ')||'Sin recomendación'}</div></td><td><span class="tag \${rule.active?'accept':'reject'}">\${esc(rule.status)}</span></td><td class="mono">\${esc(rule.affectedTrades)}</td><td class="mono \${valueClass(rule.profitGenerated)}">\${money(rule.profitGenerated)}</td><td class="mono">\${fmtNum(rule.drawdownReduced,2)}</td><td class="mono \${valueClass(rule.impactScore)}">\${fmtNum(rule.impactScore,2)}</td><td>\${esc(rule.evidenceLevel||rule.verdict||'N/D')}</td></tr>\`).join('');document.getElementById('changesTimeline').innerHTML=state.rules.map(rule=>\`<div class="timeline-event"><div class="timeline-time">\${fmtDate(rule.date)}</div><div class="timeline-title">\${esc(rule.name)} · \${esc(rule.status)}</div><div class="timeline-detail">\${esc(rule.reason)} · actor \${esc(rule.actor)} · impacto \${fmtNum(rule.impactScore,2)}</div></div>\`).join('')}
async function init(){try{const [list,rules]=await Promise.all([api('/api/knowledge/trades?limit=100'),api('/api/knowledge/rules')]);state.decisions=list.decisions||[];state.rules=rules.rules||[];document.getElementById('decisionCount').textContent=state.decisions.length+' decisiones';renderList();renderRules();const options=state.decisions.slice(0,80).map(row=>\`<option value="\${esc(row.ref)}">\${esc(decisionLabel(row))}</option>\`).join('');document.getElementById('diffLeft').innerHTML=options;document.getElementById('diffRight').innerHTML=options;if(state.decisions[1])document.getElementById('diffRight').value=state.decisions[1].ref;if(state.decisions[0])selectDecision(state.decisions[0].ref);icon()}catch(error){document.getElementById('decisionList').innerHTML='<div class="empty">'+esc(error.message)+'</div>'}}
document.getElementById('decisionSearch').oninput=renderList;document.getElementById('decisionKind').onchange=renderList;document.getElementById('compareBtn').onclick=compare;init();
</script>
</body></html>`; }

module.exports = { getKnowledgeHTML };
